### ISSUE TITLE
:pushpin:リアクション後付けでのピン止めができない

### ISSUE THREAD

**Issue by jaotan** [jaoafa/jaotan.ts#186]
# 不具合報告

📌リアクションの後付けでピン止めをできる機能が、リアクションしても全く反応しない

## 不具合と思われるメッセージ (または報告)

2023-11-05 16:34:36.947 に送信された `kohonayoshi` による `#Cities: Skylines` でのメッセージ

メッセージURL: https://discord.com/channels/1138605145660326040/1169662334831181905/1170627213696184350

## 不具合報告者

`kohonayoshi` (`315726390844719114`)

**Comment by book000** [comment]
https://github.com/jaoafa/jaotan.ts/blob/58e8a82b6fa7851c2bad1591a2b21cfebd21aeb4/src/events/pin-reaction.ts#L36

このif分岐でスレッドも対象にする
