### ISSUE TITLE
何か機能を一個実装してみよう会の実施

### ISSUE THREAD

**Issue by book000** [jaoafa/jaotan.ts#28]

**Comment by book000** [comment]
## Discord Botの初期セットアップ

1. Botトークンを作成
2. Botテスト用サーバの作成
3. Botをテスト用サーバに参加させる

---

## 開発環境の作成

1. ローカルの開発環境構築
  - Node.js (node -vが実行できるまで)
  - Yarn or pnpm
  - Visual Studio Code
2. リポジトリのフォーク
3. クローン + Visual Studio Code で開く
4. yarn install の実行

---

## プロジェクトへの理解

1. 使用しているライブラリを理解する
2. フォルダ構成を理解する

## 設計

1. どんなコマンドが必要か考える（or Javajaotan2で実装済みのコマンドをそれぞれに振って、このコマンドはどう作れば良いか考えてもらう）
  - 初心者には potato コマンドとか単一メッセージの応答
  - 他の言語でプログラミングやったことある人は bassline とか引数を使うもの
  - 中級者は…なにしようねえ
2. コマンドの内部構造を考える。必要となる結果を生み出すために、どんな風にしたらいいかな？ってのを考えてもらう
3. 実装に必要な知識を得る（2,3逆かも）

## 実装

1. 実装する
2. 動作確認する

## コミット・プルリクエスト

**Comment by book000** [comment]
いいとこ3時間で実施。14〜17時で50分くらいやったら10分休憩

- 事前準備: Node.js、Visual Studio Codeのインストール。14時までにこれを実施する（適宜対応しても良き）
  - Node.jsのインストール方法はヒラタケあたりに振っても…まあ…
  - 出来る人はリポジトリのフォークとクローン

---

知ろう

- 最初の10分で `jaotan.ts` とは何かの説明、今後のスケジュール感の説明
- 使っているプログラミング言語・ライブラリのさくっとした説明。TypeScript、Node.js、discord.js、eslint / prettier
- やってない人: リポジトリのフォークとクローン

ここまで30分くらい。やってない人向けに10分くらいでフォーククローン実施、そのあと10分休憩（計50分）

---

手を動かそう

- Visual Studio Code で開く
- 依存パッケージのインストールをしてみよう: ここまで5分 （インストールコマンド叩いたら並行して次）
- Botの作成とテストサーバの作成、テストサーバへのBot追加: 20分
- フォルダを眺めてみよう（フォルダ構成の理解）: 5分
- 実際に動かしてみよう（テストサーバで動かす）: 5分
- 実際のコマンド実装を見てみよう（ざっくりとしたコマンドの理解）: 10分

休憩10分

---

考えよう

- コマンドを作りたい
- どんなコマンドがいいだろう？もしくは、こんなコマンドを作ってみてほしいって振る（inputとoutputのみ提示する）: 10分
- 内部設計を行う。inputとoutputを繋げるために、中でどんな処理が必要になるだろう？discord.jsではどんなことができるんだろう？: 40分

休憩

---

作ってみよう

- コマンド用のファイルを作る
- コマンドを登録する
- コマンドを実装する: ここまで30分
- コミットして、プルリクエストを作ってみよう（途中の場合はドラフト）: 20分

終了

**Comment by book000** [comment]
スライドをGoogleスライドで作って、配布した方が良さそう。それをGoLiveしつつ…かな

**Comment by book000** [comment]
日程は以下の感じかな？

- 〜8/26: スライド資料作成、ゆうあ氏あたりにチェックしてもらう
- 8/27〜9/1: 告知（#dev-changes、#announcementにもリンクとして告知）
- 9/2: 実施？

**Comment by book000** [comment]
簡単（プログラミングまずやったことない人）

- tmttmt: 単一メッセージ返すだけ
- potato: 単一メッセージ返すだけ
- powa: 単一メッセージ返すだけ
- super: 単一メッセージ返すだけ
- akakese: 最初は引数なしでコマンド実行者に。その後引数のユーザへ
- recid: 最初は引数なし、出来たら引数あり
- alpha: 最初は引数なし。出来たら引数あり
- bassline: 最初は引数なし（ヒラタケへのみ）、出来たら引数あり

中級者（他言語とかでプログラミング経験がある人）

- translate系、まずはtojaかな？
- typo
-

**Comment by book000** [comment]
資料作るの秋田

**Comment by Omuretsu** [comment]
👀

**Comment by book000** [comment]
- Node.js: 普通のインストール or nvmとかそのへん
- VS Code: 普通にインストール
- リポジトリフォーク: ふつうに
- リポジトリクローン: ふつうに
